#!/bin/zsh
# # http://webtech-walker.com/archive/2008/12/15101251.html
# export LSCOLORS=gxfxxxxxcxxxxxxxxxgxgx
# export LS_COLORS='di=01;36:ln=01;35:ex=01;32'
# zstyle ':completion:*' list-colors 'di=36' 'ln=35' 'ex=32'
function ls(){
    command ls -G --color $@ 2>/dev/null||command ls -G $@
}
